// Warning! This file is autogenerated.$
// Source file ../../../../../../../../codegen/classes.kts$
package com.v2soft.flowtest.base

data class BufferDescription (
    val blockSize : Int,
    val blockCount : Int,
    val lastBlockSize : Int,
    val blocks : LongArray,
)
