// Warning! This file is autogenerated.
// Source file ../../../../../../../../codegen/classes.kts
package com.v2soft.flowtest.base

enum class HashMethod {
    CRC32,
    MD5
}

interface InputFlowBase {
//    fun registerAsyncHandler(handler : InputFlowResponseHandler?)
    fun getSize() : Long
    fun getBlock(blockId: Int, array : ByteArray) : Int
//    fun getBlockAsync(blockId: Int, array : ByteArray, requestTag : Int)
    fun getBlockSize(): Int
    fun getBlockHash(blockId: Int): ByteArray
}
