// Warning! This file is autogenerated.
// Source file ../../../../../../../../codegen/classes.kts
package com.v2soft.flowtest.base

interface InputFlowResponseHandler {
fun handleBlock(requestTag : Int, size : Int, array : ByteArray)
}
