// Warning! This file is autogenerated.
// Source file ../../../../../../../../codegen/classes.kts
package com.v2soft.flowtest.base

enum class HashMethod {
    CRC32,
    MD5
}

interface InputBufferBase {
    /**
     * Size of buffer in bytes.
     */
    fun getSize() : Long

    /**
     * Whole number of blocks in this buffer. I.e size / blockSize.
     */
    fun getBlocksCount(): Int
    fun getBlock(blockId: Int, array : ByteArray, offset: Int) : Int
    fun getBlockSize(): Int
    fun getBlockHash(blockId: Int): ByteArray
}
