// Warning! This file is autogenerated.
// Source file ../../../../../../../../codegen/classes.kts
package com.v2soft.flowtest.base

interface InputFlowBase {
fun registerAsyncHandler(handler : InputFlowResponseHandler?)
fun getSize() : Long
fun getBlock(offset : Long, size : Int, array : ByteArray) : Int
fun getBlockAsync(offset : Long, size : Int, array : ByteArray, requestTag : Int)
}
