// Warning! This file is autogenerated.
// Source file ../../../../../../../../codegen/classes.kts
package com.v2soft.flowtest.base

enum class HashMethod {
    CRC32,
    MD5
}

interface InputFlowBase {
    fun getSize() : Long
    fun getBlock(blockId: Int, array : ByteArray) : Int
    fun getBlockSize(): Int
    fun getBlockHash(blockId: Int): ByteArray
}
